// <auto-generated />
using System;
using FscAppLibrary.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FscAppLibrary.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    [Migration("20230914120305_Service")]
    partial class Service
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FscAppLibrary.Models.ComentariuModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ComentariuDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ComentariuDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("ComentariuName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("ComentariuVotes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Comentarii");
                });

            modelBuilder.Entity("FscAppLibrary.Models.FormularDeContactModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FormularDescription")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("FormularEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormularName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FormularPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Formulare");
                });

            modelBuilder.Entity("FscAppLibrary.Models.ProgramareOnlineModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ProgramareDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProgramareDescription")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("ProgramareEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProgramareName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("ProgramarePersons")
                        .HasColumnType("int");

                    b.Property<string>("ProgramarePhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProgramareService")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProgramareTimp")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Programari");
                });

            modelBuilder.Entity("FscAppLibrary.Models.ReviewModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ComentariuId")
                        .HasColumnType("int");

                    b.Property<int>("ReviewComents")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReviewDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReviewDescription")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("ReviewName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<double>("ReviewRate")
                        .HasColumnType("float");

                    b.Property<int>("ReviewVotes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ComentariuId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("FscAppLibrary.Models.ReviewModel", b =>
                {
                    b.HasOne("FscAppLibrary.Models.ComentariuModel", "Comentariu")
                        .WithMany()
                        .HasForeignKey("ComentariuId");

                    b.Navigation("Comentariu");
                });
#pragma warning restore 612, 618
        }
    }
}
